language: python
python:
  - "3.6"
before_install:
  - pip install pycodestyle codecov
  - python3 setup.py install
script:
  - pycodestyle --exclude=venv --ignore=E501 .
  - pytest
  - coverage run --parallel-mode --branch --source=. -m unittest discover -bv
  - cp add_parser.py.sample add_parser.py
  - coverage run --parallel-mode --branch --source=. -m unittest discover -bv
  - coverage combine
  - coverage report -m
after_success:
  - codecov